name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "aceca4eeb5a79092eabefaa75fcb72b701d02205"

[[require]]
name = "LeanMqtt"
path = "../"
