import LeanMqtt.Primitives.UInt.Basic
import LeanMqtt.Primitives.VarInt.Basic

namespace Mqtt
open Mqtt

/- ========================= PktKind ========================= -/

inductive PktKind where
  | connect | connack
  | publish | puback | pubrec | pubrel | pubcomp
  | subscribe | suback | unsubscribe | unsuback | pingreq | pingresp
  | disconnect
  | auth
deriving Repr, BEq

def PktKind.encode : PktKind → BitVec 4
  | .connect     => 1   | .connack     => 2   | .publish     => 3
  | .puback      => 4   | .pubrec      => 5   | .pubrel      => 6
  | .pubcomp     => 7   | .subscribe   => 8   | .suback      => 9
  | .unsubscribe => 10  | .unsuback    => 11  | .pingreq     => 12
  | .pingresp    => 13  | .disconnect  => 14  | .auth        => 15

def PktKind.decode? : BitVec 4 → Option PktKind
  | 1 => some .connect    | 2 => some .connack     | 3 => some .publish
  | 4 => some .puback     | 5 => some .pubrec      | 6 => some .pubrel
  | 7 => some .pubcomp    | 8 => some .subscribe   | 9 => some .suback
  | 10 => some .unsubscribe| 11 => some .unsuback  | 12 => some .pingreq
  | 13 => some .pingresp  | 14 => some .disconnect | 15 => some .auth
  | _ => none

instance : Inhabited PktKind where
  default := .pingreq

/- =========================  Flags ========================= -/

abbrev QoSBits := { q : BitVec 2 // q ≠ 0b11 }

structure PublishFlags where
  dup    : BitVec 1
  qos    : QoSBits
  retain : BitVec 1
deriving Repr, BEq

/-- A simple type alias for bits that must match a specific constant value. -/
abbrev ConstBits (nBits : Nat) (v : BitVec nBits) := { b : BitVec nBits // b = v }

def PktFlags : PktKind → Type
  | .connect     => ConstBits 4 0b0000
  | .connack     => ConstBits 4 0b0000
  | .publish     => PublishFlags
  | .puback      => ConstBits 4 0b0000
  | .pubrec      => ConstBits 4 0b0000
  | .pubrel      => ConstBits 4 0b0010
  | .pubcomp     => ConstBits 4 0b0000
  | .subscribe   => ConstBits 4 0b0010
  | .suback      => ConstBits 4 0b0000
  | .unsubscribe => ConstBits 4 0b0010
  | .unsuback    => ConstBits 4 0b0000
  | .pingreq     => ConstBits 4 0b0000
  | .pingresp    => ConstBits 4 0b0000
  | .disconnect  => ConstBits 4 0b0000
  | .auth        => ConstBits 4 0b0000

def PktFlags.encode : (k : PktKind) → PktFlags k → BitVec 4
  | .publish, f     => f.dup ++ f.qos.val ++ f.retain
  -- For all constant bits, we just extract the underlying BitVec value
  | .pubrel, f      => f.val
  | .subscribe, f   => f.val
  | .unsubscribe, f => f.val
  | .connect, f     => f.val
  | .connack, f     => f.val
  | .puback, f      => f.val
  | .pubrec, f      => f.val
  | .pubcomp, f     => f.val
  | .suback, f      => f.val
  | .unsuback, f    => f.val
  | .pingreq, f     => f.val
  | .pingresp, f    => f.val
  | .disconnect, f  => f.val
  | .auth, f        => f.val

/--
  Decodes and validates the raw bits. If successful, it constructs the
  dependent type `PktFlags k` using the proofs generated by the `if h : ...` checks.
-/
def PktFlags.decode? (k : PktKind) (b : BitVec 4) : Option (PktFlags k) :=
  match k with
  | .publish =>
      let dup    := b.extractLsb 3 3
      let qos    := b.extractLsb 2 1
      let retain := b.extractLsb 0 0
      if qos = 0b11 then none
      else if h : qos ≠ 3 then
        some { dup, qos := ⟨qos, h⟩, retain }
      else
        none
  | .pubrel | .subscribe | .unsubscribe =>
      if h : b = 0b0010 then some ⟨b, h⟩ else none
  | .connect | .connack | .puback | .pubrec | .pubcomp | .suback
  | .unsuback | .pingreq | .pingresp | .disconnect | .auth =>
      if h : b = 0b0000 then some ⟨b, h⟩ else none

/- ========================= FixedHeader ========================= -/

structure FixedHeader where
  kind  : PktKind
  flags : PktFlags kind
  size  : VarInt

def FixedHeader.serialize (h : FixedHeader) : List UInt8 :=
  let byte := h.kind.encode ++ PktFlags.encode h.kind h.flags
  [UInt8.ofBitVec byte] ++ h.size.serialize

def FixedHeader.parser : Parser FixedHeader := do
  let byte ← UInt8.parser
  -- TODO: explore how we could create a custom BitVec primitive
  --       to improve proofs
  let bv := byte.toBitVec

  let kindBits  := bv.extractLsb 7 4
  let flagsBits := bv.extractLsb 3 0

  let kind ← PktKind.decode? kindBits
  let flags ← PktFlags.decode? kind flagsBits

  let size ← VarInt.parser
  return { kind, flags, size }

end Mqtt
