import LeanMqtt.Primitives.UInt.Basic
import LeanMqtt.Primitives.VarInt.Basic
import LeanMqtt.Primitives.ConstVal.Basic
import LeanMqtt.Helpers.EnumUtils

namespace Mqtt
open Mqtt

/-!
# Fixed Header

This module implements the MQTT Fixed Header, which is the mandatory first part
of every MQTT packet. It contains the packet type (`PktKind`), the packet-specific
flags (`PktFlags`), and the remaining length of the packet (`size` as a `VarInt`).

It utilizes dependent types to guarantee that the parsed flags perfectly match the
type of packet specified by the packet kind.
-/

/- ========================================================================= -/
/-! ## Packet Kind (`PktKind`) -/

/--
Defines the 4-bit identifier for the type of MQTT control packet.

Functions `PktKind.encode` and `PktKind.decode?` are automatically generated by the
`enum_with_codec` macro.
-/
enum_with_codec PktKind : BitVec 4 where
  | connect     => 1
  | connack     => 2
  | publish     => 3
  | puback      => 4
  | pubrec      => 5
  | pubrel      => 6
  | pubcomp     => 7
  | subscribe   => 8
  | suback      => 9
  | unsubscribe => 10
  | unsuback    => 11
  | pingreq     => 12
  | pingresp    => 13
  | disconnect  => 14
  | auth        => 15

/- ========================================================================= -/
/-! ## Packet Flags (`PktFlags`) -/

abbrev QoSBits := { q : BitVec 2 // q ≠ 0b11 }

structure PublishFlags where
  dup    : BitVec 1
  qos    : QoSBits
  retain : BitVec 1
deriving Repr, BEq

/--
Defines the 4-bit flags specific to each packet kind.

Most packets have constant flags mandated by the specification, but `PUBLISH` uses them
dynamically to indicate duplicate delivery, QoS level, and the retain flag.
-/
def PktFlags : PktKind → Type
  | .connect     => ConstVal (BitVec 4) (0b0000)
  | .connack     => ConstVal (BitVec 4) (0b0000)
  | .publish     => PublishFlags
  | .puback      => ConstVal (BitVec 4) (0b0000)
  | .pubrec      => ConstVal (BitVec 4) (0b0000)
  | .pubrel      => ConstVal (BitVec 4) (0b0010)
  | .pubcomp     => ConstVal (BitVec 4) (0b0000)
  | .subscribe   => ConstVal (BitVec 4) (0b0010)
  | .suback      => ConstVal (BitVec 4) (0b0000)
  | .unsubscribe => ConstVal (BitVec 4) (0b0010)
  | .unsuback    => ConstVal (BitVec 4) (0b0000)
  | .pingreq     => ConstVal (BitVec 4) (0b0000)
  | .pingresp    => ConstVal (BitVec 4) (0b0000)
  | .disconnect  => ConstVal (BitVec 4) (0b0000)
  | .auth        => ConstVal (BitVec 4) (0b0000)

def PktFlags.encode : (k : PktKind) → PktFlags k → BitVec 4
  | .publish, f     => f.dup ++ f.qos.val ++ f.retain
  -- For all constant bits, we just extract the underlying BitVec value
  | .pubrel, f      => f.val
  | .subscribe, f   => f.val
  | .unsubscribe, f => f.val
  | .connect, f     => f.val
  | .connack, f     => f.val
  | .puback, f      => f.val
  | .pubrec, f      => f.val
  | .pubcomp, f     => f.val
  | .suback, f      => f.val
  | .unsuback, f    => f.val
  | .pingreq, f     => f.val
  | .pingresp, f    => f.val
  | .disconnect, f  => f.val
  | .auth, f        => f.val

/--
Decodes and validates the raw bits. If successful, it constructs the
dependent type `PktFlags k` using the proofs generated by the `if h : ...` checks.
-/
def PktFlags.decode? (k : PktKind) (b : BitVec 4) : Option (PktFlags k) :=
  match k with
  | .publish =>
      let dup    := b.extractLsb 3 3
      let qos    := b.extractLsb 2 1
      let retain := b.extractLsb 0 0
      if qos = 0b11 then none
      else if h : qos ≠ 3 then
        some { dup, qos := ⟨qos, h⟩, retain }
      else
        none
  | .pubrel | .subscribe | .unsubscribe =>
      if h : b = 0b0010 then some ⟨b, h⟩ else none
  | .connect | .connack | .puback | .pubrec | .pubcomp | .suback
  | .unsuback | .pingreq | .pingresp | .disconnect | .auth =>
      if h : b = 0b0000 then some ⟨b, h⟩ else none

/- ========================================================================= -/
/-! ## Fixed Header Structure (`FixedHeader`) -/

/--
Fixed Header of an MQTT control packet.

Combines the packet kind, the dependently-typed packet flags, and the remaining
size into the final `FixedHeader` structure.
-/
structure FixedHeader where
  kind  : PktKind
  flags : PktFlags kind
  -- TODO: model verification for `size` being indeed equal to the remaining byte length
  size  : VarInt

def FixedHeader.serialize (h : FixedHeader) : List UInt8 :=
  let byte := h.kind.encode ++ PktFlags.encode h.kind h.flags
  [UInt8.ofBitVec byte] ++ h.size.serialize

def FixedHeader.parser : Parser FixedHeader := do
  let byte ← UInt8.parser
  -- TODO: explore how we could create a custom BitVec primitive
  --       to improve proofs
  let bv := byte.toBitVec

  let kindBits  := bv.extractLsb 7 4
  let flagsBits := bv.extractLsb 3 0

  let kind ← PktKind.decode? kindBits
  let flags ← PktFlags.decode? kind flagsBits

  let size ← VarInt.parser
  return { kind, flags, size }

end Mqtt
