import Lean
import LeanMqtt.Core.Codec

namespace Mqtt
open Mqtt

/-!
# Predicate Types

This module defines `PredType`, a generic primitive for fields that are only
correct when a specific set of runtime constraints (predicates) holds true.
It also introduces the `ensure!` macro for ergonomically building constraint lists.
-/

/- ========================================================================= -/
/-! ## Conditions -/
structure Condition where
  prop : Prop
  decd : Decidable prop
  desc : String

instance (c : Condition) : Decidable c.prop := c.decd

/- ========================================================================= -/
/-! ## Predicate Type (`PredType`) -/

abbrev AllHold {α : Type} (gen : α → List Condition) (val : α) : Prop :=
  ∀ c ∈ gen val, c.prop

/--
A subtype where the given value `val` satisfies all conditions generated by `gen`.
This is used to enforce protocol invariants (e.g. reserved bits must be 0) at
the type level.

### Example
```lean
def EvenBelow10 (n : Nat) : List Condition :=
  [ ensure! n < 10,
    ensure! n % 2 = 0 ]

abbrev MyType := PredType Nat EvenBelow10

-- To construct a value manually, provide a proof that the conditions hold:
def myVal : MyType := ⟨4, by decide⟩
```
-/
abbrev PredType (α : Type) (gen : α → List Condition) : Type :=
  { val : α // AllHold gen val }

theorem PredType.get_proof {α : Type} {gen : α → List Condition} (v : PredType α gen)
    (idx : Nat) (h_idx : idx < (gen v.val).length := by exact of_decide_eq_true rfl) :
    ((gen v.val).get ⟨idx, h_idx⟩).prop :=
  v.property _ (List.get_mem ..)

def PredType.serialize {α : Type} [c : Codec α] {gen : α → List Condition} (v : PredType α gen) : List UInt8 :=
  @Codec.serialize α c v.val

def PredType.parser {α : Type} [c : Codec α] (gen : α → List Condition) : Parser (PredType α gen) := do
  let val ← @Codec.parser α c
  if h : AllHold gen val then
    return ⟨val, h⟩
  else
    failure

/- ========================================================================= -/
/-! ## Ensure Macro -/

/--
A macro that constructs a `Condition` from a proposition, automatically capturing
the expression as a string literal for the description. This makes it easy to
build lists of constraints for `PredType`.

### Example
```lean
def ConnectFlagsPred (b : UInt8) : List Condition :=
  [ ensure! b.toBitVec.extractLsb 0 0 = 0 ]
```
-/
macro "ensure! " p:term : term =>
  let desc := Lean.Syntax.mkStrLit (toString p.raw)
  `( { prop := $p, decd := inferInstance, desc := $desc } )

end Mqtt
