name = "LeanMqtt"
version = "0.1.0"
defaultTargets = ["leanmqtt"]

[[lean_lib]]
name = "LeanMqtt"

[[lean_lib]]
name = "Helpers"

[[lean_exe]]
name = "leanmqtt"
root = "Main"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "495c008c3e3f4fb4256ff5582ddb3abf3198026f"
