name = "LeanMqtt"
version = "0.1.0"
defaultTargets = ["leanmqtt"]

[[lean_lib]]
name = "LeanMqtt"

[[lean_lib]]
name = "Helpers"

[[lean_exe]]
name = "leanmqtt"
root = "Main"

# Not used in the current version
# [[require]]
# name = "batteries"
# scope = "leanprover-community"
# rev = "023ce7d62a0531e22a5331e20b587817a80d49ff"
