name = "LeanMqtt"
version = "0.1.0"
defaultTargets = ["leanmqtt"]

[[lean_lib]]
name = "LeanMqtt"

[[lean_lib]]
name = "Helpers"

[[lean_exe]]
name = "leanmqtt"
root = "Main"

# Not used in the current version
# [[require]]
# name = "batteries"
# scope = "leanprover-community"
# rev = "4488d40d070b9700d4d5a6aa342f0d40c31b2a2d"
