import LeanMqtt.Primitives.UInt.Basic
import LeanMqtt.Primitives.Str.Basic
import LeanMqtt.Primitives.OptType.Basic
import LeanMqtt.Primitives.ConstVal.Basic
import LeanMqtt.Primitives.PredType.Basic
import LeanMqtt.Packets.FixedHeader.Basic
import LeanMqtt.Packets.VarHeader.Properties.Basic
import LeanMqtt.Packets.ReasonCode.Basic

namespace Mqtt
open Mqtt

/-!
# Variable Header Variations

This module defines the specific Variable Header structures for each of the 15 MQTT
control packet types. It enforces protocol rules at the type level (e.g., verifying
that `ConnectFlags` reserved bits are 0) and provides precise serialization and
parsing implementations for each packet type.
-/

/- ========================================================================= -/
/-! ## CONNECT Variable Header (`Var_Connect`) -/

def ConnectFlagsPred (b : UInt8) : List Condition :=
  let bv := b.toBitVec
  let reserved    := bv.extractLsb 0 0
  let will_flag   := bv.extractLsb 2 2
  let will_qos    := bv.extractLsb 4 3
  let will_retain := bv.extractLsb 5 5
  [ ensure! reserved = 0,
    ensure! will_flag = 0 → will_qos = 0 ∧ will_retain = 0,
    ensure! will_qos ≠ 3
  ]

abbrev ConnectFlags := PredType UInt8 ConnectFlagsPred

-- TODO: All these fields should be automatically generated by a macro
def ConnectFlags.clean_start (f : ConnectFlags) : Bool := f.val.toBitVec.extractLsb 1 1 = 1
def ConnectFlags.will_flag   (f : ConnectFlags) : Bool := f.val.toBitVec.extractLsb 2 2 = 1
def ConnectFlags.will_qos    (f : ConnectFlags) : QoSBits :=
  let qos := f.val.toBitVec.extractLsb 4 3
  ⟨qos, PredType.get_proof f 2⟩
def ConnectFlags.will_retain (f : ConnectFlags) : Bool := f.val.toBitVec.extractLsb 5 5 = 1
def ConnectFlags.password    (f : ConnectFlags) : Bool := f.val.toBitVec.extractLsb 6 6 = 1
def ConnectFlags.username    (f : ConnectFlags) : Bool := f.val.toBitVec.extractLsb 7 7 = 1

structure Var_Connect where
  -- TODO: As per MQTT-3.1.2-2, the server may decide to respond when the
  -- protocol name (or other structures) is malformed. We can deal with
  -- this in two ways:
  -- 1. Implement a type for "may fail"
  -- 2. Specify this in a parser error (need to move away from `Option`)
  protocol_name    : ConstVal Str (WithByteSize.of "MQTT")
  protocol_version : ConstVal UInt8 5
  connect_flags    : ConnectFlags
  props            : Properties

def Var_Connect.serialize (v : Var_Connect) : List UInt8 :=
  v.protocol_name.serialize ++
  v.protocol_version.serialize ++
  v.connect_flags.serialize ++
  v.props.serialize

def Var_Connect.parser : Parser Var_Connect := do
  let protocol_name ← ConstVal.parser (WithByteSize.of "MQTT")
  let protocol_version ← ConstVal.parser 5
  let connect_flags ← PredType.parser ConnectFlagsPred
  let props ← Properties.parser
  return { protocol_name, protocol_version, connect_flags, props }

/- ========================================================================= -/
/-! ## CONNACK Variable Header (`Var_Connack`) -/

def ConnackFlagsProp (b : UInt8) : List Condition :=
  let bv := b.toBitVec
  let reserved := bv.extractLsb 7 1
  [ ensure! reserved = 0 ]

abbrev ConnackFlags := PredType UInt8 ConnackFlagsProp

def ConnackFlags.session_present (f : ConnackFlags) : Bool := f.val.toBitVec.extractLsb 0 0 = 1

structure Var_Connack where
  ack_flags   : ConnackFlags
  reason_code : ReasonCode .connack
  props       : Properties

def Var_Connack.serialize (v : Var_Connack) : List UInt8 :=
  v.ack_flags.serialize ++
  v.reason_code.serialize ++
  v.props.serialize

def Var_Connack.parser : Parser Var_Connack := do
  let ack_flags   ← PredType.parser ConnackFlagsProp
  let reason_code ← ReasonCode.parser .connack
  let props       ← Properties.parser
  return { ack_flags, reason_code, props }

/- ========================================================================= -/
/-! ## PUBLISH Variable Header (`Var_Publish`) -/

def TopicNameProp (s : Str) : List Condition :=
  [ ensure! ¬ s.val.contains '+',
    ensure! ¬ s.val.contains '#'
  ]

abbrev TopicName := PredType Str TopicNameProp

structure Var_Publish (qos : QoSBits) where
  topic_name : TopicName
  packet_id  : OptType UInt16 (qos.val > 0)
  props      : Properties

def Var_Publish.serialize {qos : QoSBits} (v : Var_Publish qos) : List UInt8 :=
  v.topic_name.serialize ++
  v.packet_id.serialize ++
  v.props.serialize

def Var_Publish.parser (qos : QoSBits) : Parser (Var_Publish qos) := do
  let topic_name ← PredType.parser TopicNameProp
  let packet_id ← OptType.parser (qos.val > 0)
  let props ← Properties.parser

  return { topic_name, packet_id, props }

/- ========================================================================= -/
/-! ## PUBACK Variable Header (`Var_Puback`) -/

structure Var_Puback where
  packet_id   : UInt16
  -- TODO: The Reason Code and Properties can be omitted if the
  -- Reason Code is 0x00 (Success) and there are no Properties.
  reason_code : ReasonCode .puback
  props       : Properties

def Var_Puback.serialize (v : Var_Puback) : List UInt8 :=
  v.packet_id.serialize ++
  v.reason_code.serialize ++
  v.props.serialize

def Var_Puback.parser : Parser (Var_Puback) := do
  let packet_id ← UInt16.parser
  let reason_code ← ReasonCode.parser .puback
  let props ← Properties.parser
  return { packet_id, reason_code, props }

/- ========================================================================= -/
/-! ## PUBREC Variable Header (`Var_Pubrec`) -/

structure Var_Pubrec where
  packet_id   : UInt16
  -- TODO: The Reason Code and Properties can be omitted if the
  -- Reason Code is 0x00 (Success) and there are no Properties.
  reason_code : ReasonCode .pubrec
  props       : Properties

def Var_Pubrec.serialize (v : Var_Pubrec) : List UInt8 :=
  v.packet_id.serialize ++
  v.reason_code.serialize ++
  v.props.serialize

def Var_Pubrec.parser : Parser (Var_Pubrec) := do
  let packet_id ← UInt16.parser
  let reason_code ← ReasonCode.parser .pubrec
  let props ← Properties.parser
  return { packet_id, reason_code, props }

/- ========================================================================= -/
/-! ## PUBREL Variable Header (`Var_Pubrel`) -/

structure Var_Pubrel where
  packet_id   : UInt16
  -- TODO: The Reason Code and Properties can be omitted if the
  -- Reason Code is 0x00 (Success) and there are no Properties.
  reason_code : ReasonCode .pubrel
  props       : Properties

def Var_Pubrel.serialize (v : Var_Pubrel) : List UInt8 :=
  v.packet_id.serialize ++
  v.reason_code.serialize ++
  v.props.serialize

def Var_Pubrel.parser : Parser (Var_Pubrel) := do
  let packet_id ← UInt16.parser
  let reason_code ← ReasonCode.parser .pubrel
  let props ← Properties.parser
  return { packet_id, reason_code, props }

/- ========================================================================= -/
/-! ## PUBCOMP Variable Header (`Var_Pubcomp`) -/

structure Var_Pubcomp where
  packet_id   : UInt16
  -- TODO: The Reason Code and Properties can be omitted if the
  -- Reason Code is 0x00 (Success) and there are no Properties.
  reason_code : ReasonCode .pubcomp
  props       : Properties

def Var_Pubcomp.serialize (v : Var_Pubcomp) : List UInt8 :=
  v.packet_id.serialize ++
  v.reason_code.serialize ++
  v.props.serialize

def Var_Pubcomp.parser : Parser (Var_Pubcomp) := do
  let packet_id ← UInt16.parser
  let reason_code ← ReasonCode.parser .pubcomp
  let props ← Properties.parser
  return { packet_id, reason_code, props }

/- ========================================================================= -/
/-! ## SUBSCRIBE Variable Header (`Var_Subscribe`) -/

structure Var_Subscribe where
  packet_id : UInt16
  props     : Properties

def Var_Subscribe.serialize (v : Var_Subscribe) : List UInt8 :=
  v.packet_id.serialize ++
  v.props.serialize

def Var_Subscribe.parser : Parser (Var_Subscribe) := do
  let packet_id ← UInt16.parser
  let props ← Properties.parser
  return { packet_id, props }

/- ========================================================================= -/
/-! ## SUBACK Variable Header (`Var_Suback`) -/

structure Var_Suback where
  packet_id : UInt16
  props     : Properties

def Var_Suback.serialize (v : Var_Suback) : List UInt8 :=
  v.packet_id.serialize ++
  v.props.serialize

def Var_Suback.parser : Parser (Var_Suback) := do
  let packet_id ← UInt16.parser
  let props ← Properties.parser
  return { packet_id, props }

/- ========================================================================= -/
/-! ## UNSUBSCRIBE Variable Header (`Var_Unsubscribe`) -/

structure Var_Unsubscribe where
  packet_id : UInt16
  props     : Properties

def Var_Unsubscribe.serialize (v : Var_Unsubscribe) : List UInt8 :=
  v.packet_id.serialize ++
  v.props.serialize

def Var_Unsubscribe.parser : Parser (Var_Unsubscribe) := do
  let packet_id ← UInt16.parser
  let props ← Properties.parser
  return { packet_id, props }

/- ========================================================================= -/
/-! ## UNSUBACK Variable Header (`Var_Unsuback`) -/

structure Var_Unsuback where
  packet_id : UInt16
  props     : Properties

def Var_Unsuback.serialize (v : Var_Unsuback) : List UInt8 :=
  v.packet_id.serialize ++
  v.props.serialize

def Var_Unsuback.parser : Parser (Var_Unsuback) := do
  let packet_id ← UInt16.parser
  let props ← Properties.parser
  return { packet_id, props }

/- ========================================================================= -/
/-! ## PINGREQ Variable Header (`Var_Pingreq`) -/

abbrev Var_Pingreq  := Unit

def Var_Pingreq.serialize (_ : Var_Pingreq) : List UInt8 := []
def Var_Pingreq.parser : Parser (Var_Pingreq) := return ()

/- ========================================================================= -/
/-! ## PINGRESP Variable Header (`Var_Pingresp`) -/

abbrev Var_Pingresp := Unit

def Var_Pingresp.serialize (_ : Var_Pingresp) : List UInt8 := []
def Var_Pingresp.parser : Parser (Var_Pingresp) := return ()

/- ========================================================================= -/
/-! ## DISCONNECT Variable Header (`Var_Disconnect`) -/

structure Var_Disconnect where
  -- TODO: The Reason Code and Properties can be omitted if the
  -- Reason Code is 0x00 (Normal disconnection) and there are no Properties.
  reason_code : ReasonCode .disconnect
  props       : Properties

def Var_Disconnect.serialize (v : Var_Disconnect) : List UInt8 :=
  v.reason_code.serialize ++
  v.props.serialize

def Var_Disconnect.parser : Parser (Var_Disconnect) := do
  let reason_code ← ReasonCode.parser .disconnect
  let props ← Properties.parser
  return { reason_code, props }

/- ========================================================================= -/
/-! ## AUTH Variable Header (`Var_Auth`) -/

structure Var_Auth where
  -- TODO: The Reason Code and Properties can be omitted if the
  -- Reason Code is 0x00 (Success) and there are no Properties.
  reason_code : ReasonCode .auth
  props       : Properties

def Var_Auth.serialize (v : Var_Auth) : List UInt8 :=
  v.reason_code.serialize ++
  v.props.serialize

def Var_Auth.parser : Parser (Var_Auth) := do
  let reason_code ← ReasonCode.parser .auth
  let props ← Properties.parser
  return { reason_code, props }

end Mqtt
